### ISSUE TITLE
Update NodeJS

### ISSUE THREAD

**Issue by cg433n** [ualibraries/vagrant-ansible#2]
Let's track the latest LTS release.

**Comment by zensense** [comment]
Thanks @cg433n! I applied a couple commits on the master branch to add nvm and node back in. The node version variable is declared in the vars.yml file in the root of the repo (you can see the commit here f3a3ed30a1832bb35efd6ae0cb81b2a408b21742) We'll try node v6.9.1 for a while. And with nvm we can add other versions on a whim. 

Issue open until you pull and do a provisional test. 

Cheers!

**Comment by cg433n** [comment]
It works!
